server:
  port: 8598
spring:
  datasource:
    url:
    driver-class-name: org.postgresql.Driver
    username:
    password:

  application:
    name: person-microservice
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect